experiment_name: eastwood_split_footprint

root: data/ARL_Jackal
geotiff: ${root}/ut_campus_EPSG32614_scale03_022126.tiff

pose:
  default_file: utm_pose.csv
  delimiter: ","
  skip_header: 1
  has_header: true
  x_col: x
  y_col: y
  scene_pose_files: {}

groups:
  train:
    label: Train
    color: "#0072B0"
    linewidth: 4
    alpha: 0.8
    offset_px: [0, 0]
    scenes:
      - eastwood_2025_08_13-16_53_17
      - eastwood_2025_08_13-17_09_38

  val:
    label: Validation
    color: "#009E70"
    linewidth: 4
    alpha: 0.8
    offset_px: [0, 0]
    scenes:
      - eastwood_2025_08_13-17_15_58

  test1:
    label: Test 1
    color: "#FFAC1C"
    linewidth: 4
    alpha: 0.8
    offset_px: [0, 0]
    scenes:
      - eastwood_test_2025_08_24-12_40_56

  test2:
    label: Test 2
    color: "#FD3DB5"
    linewidth: 4
    alpha: 0.8
    offset_px: [0, 0]
    scenes:
      - eastwood_test_2025_08_24-13_32_03

viz:
  figure_size: [20, 20]
  map_alpha: 0.5
  padding_px: 80
  legend_loc: upper left
  scale_bar_m: 100
  scale_bar_font_size: 24
  dpi: 120
  hide_axes: true

output:
  path: paper_scripts/figure/footprint/eastwood_split.png
