_target_: dataset.alphatruck.AlphaTruckSequence
name: "HCFS-Second"

root: /home/bpp/data/HCFS/processed/second_trail_road_loop
geo_tiff_path: ${.root}/second_trail_road_loop.tif

ground_image_resize: [512, 512]
aerial_image_resize: [768, 768]

scenes:
  - second_trail_road_loop1
  - second_trail_road_loop2
  - second_trail_road_loop3
  - second_trail_road_loop4
  - second_trail_road_loop5
  - second_trail_road_loop6
  - second_trail_road_loop7
  - second_trail_road_loop8
  - second_trail_road_loop9
  - second_trail_road_loop10
  - second_trail_road_loop11
  - second_trail_road_loop12
  - second_trail_road_loop13
