_target_: dataset.arl_jackal.ARLJackalSequence
name: "SARA_onioncreek_action_gain_1"

root: data/ARL_Jackal
geo_tiff_path: ${.root}/onioncreek_EPSG32614_scale02_022726.tiff

ground_image_resize: [512, 512]
aerial_image_resize: [768, 768]

scenes:
  - onioncreek_teleop-00_2026-02-18-17-36-11
  - onioncreek_teleop-01_2026-02-18-17-42-21
  - onioncreek_teleop-02_2026-02-18-17-51-42
  - onioncreek_teleop-03_2026-02-18-18-06-23
  - onioncreek_teleop-04_2026-02-18-18-16-52
