_target_: dataset.alphatruck.AlphaTruckDataset
name: "AlphaTruck_HCFS_Second"

root: /scratch/quattro/datasets/HCFS-second_trail_road_loop
geo_tiff_path: ${.root}/second_trail_road_loop.tif

ground_image_resize: [512, 512]
aerial_image_resize: [768, 768]

# --- sampling parameters ---
n_poses: 128
dist_bounds: [5.0, 100.0] # (m)
r_bounds: [-90.0, 90.0] # (deg)
radial_power: 0.3

# --- data augmentation ---
center_jitter: 50.0
scale_bounds: [1.0, 3.0]
rotate_augment: True
color_augment: 1.0
depth_dropout: 0.2

train_scenes:
  - second_trail_road_loop1
  - second_trail_road_loop2
  - second_trail_road_loop4
  - second_trail_road_loop5
  - second_trail_road_loop6
  - second_trail_road_loop7
  - second_trail_road_loop8
  - second_trail_road_loop9
  - second_trail_road_loop10
  - second_trail_road_loop12
  - second_trail_road_loop13

val_scenes:
  - second_trail_road_loop3
  - second_trail_road_loop11
